on: [push]
name: build
jobs:
  runidris:
    name: Run Idris
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Idris
        uses: sergeyshpadyrev/setup-idris@v1.2
      - name: Compile program
        run: idris src/hola.idr -o main
      - name: Run program
        run: ./build/exec/hola
